(()=>{
      'use strict';
      const clientView=document.documentElement.dataset.view==='client';
      const STORAGE_KEY=clientView?'aqueduto-client-calculator-v4':'aqueduto-production-calculator-v8',LEGACY_KEY=clientView?'aqueduto-client-legacy-v4':'aqueduto-production-calculator-v7';
      const $=selector=>document.querySelector(selector),clone=value=>JSON.parse(JSON.stringify(value));
      const esc=value=>String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
      const rub=new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB',maximumFractionDigits:0}),num=new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2});
      const money=value=>rub.format(Number(value)||0),numberText=value=>num.format(Number(value)||0);
      const unitOptions=['слайд','блок','категория','бренд','фото'];
      const unitLabel=unit=>unit.charAt(0).toUpperCase()+unit.slice(1);
      const normalizeUnit=unit=>unitOptions.includes(unit)?unit:'слайд';
      const unitPlural=unit=>unit==='слайд'?'слайдов':unit==='блок'?'блоков':unit==='категория'?'категорий':unit==='бренд'?'брендов':'фото';
      const situations=[
        {field:'masterSku',name:'Мастер-артикул категории',short:'Первая полная карточка',description:'На нём проверяем мастер-концепт и собираем рабочую систему категории.'},
        {field:'standardSku',name:'Типовой SKU по утверждённой системе',short:'Типовая сборка',description:'Меняем товар, характеристики и контент без перестройки композиции.'},
        {field:'refinementSku',name:'Нетиповой SKU / адаптация шаблона',short:'Требуется адаптация',description:'Товар или набор преимуществ не укладывается в готовый шаблон.'},
        {field:'modificationSku',name:'Простая модификация',short:'Цвет, размер или комплект',description:'Композиция сохраняется, меняется модификация товара и данные.'}
      ];
      const competitorDescription='Изучаем выдачу, визуальные паттерны, аргументы и УТП, структуру карусели и точки отстройки у основных конкурентов. Определяем рекомендуемую структуру карточки, количество и типы слайдов.';
      const competitorResult='Слабые и сильные стороны до 10 основных конкурентов; направления визуальной отстройки; ориентиры по структуре карусели и подаче преимуществ.';
      const matrixAuditDescription='Аудируем товарную матрицу и исходные материалы по каждому артикулу: проверяем достаточность и качество фото, определяем объём ретуши, перегенерации и других доработок. Группируем SKU по типовым ситуациям и считаем, сколько шаблонов потребуется создать и адаптировать для всей партии.';
      const matrixAuditResult='Финальная таблица с утверждённой сметой и планом производства: перечень уникальных шаблонов, распределение SKU по типам, количество готовых и требующих доработки исходников, объём ретуши и перегенерации, статус ready / not ready по каждому артикулу.';
      const productionEstimateNote='Предварительная оценка. Точное распределение SKU по типам и стоимость единицы определим после изучения и классификации всех исходных материалов.';
      const photoGenerationEstimateNote='Предварительная оценка. Точное количество изображений для AI-генерации определим после аудита исходных материалов.';
      const rowDefinitions=[
        {id:'competitor-analysis',group:'Подготовка и старт проекта',name:'Анализ конкурентов',unit:'категория',description:competitorDescription,result:competitorResult,qty:1,enabled:true,price:null},
        {id:'product-matrix-audit',group:'Подготовка и старт проекта',name:'Аудит товарной матрицы и исходных материалов',unit:'категория',description:matrixAuditDescription,result:matrixAuditResult,qty:1,enabled:true,price:null},
        {id:'design-system',group:'Тестирование',name:'Концепты обложки для A/B-теста CTR',unit:'слайд',description:'3 концепта обложки для A/B-теста CTR; выбранную систему масштабируем на остальные слайды.',qty:3,enabled:true,price:null},
        {id:'design-system-development',group:'Система и производство',name:'Разработка дизайн-системы бренда',unit:'бренд',description:'Фиксированная разработка дизайн-системы категории.',qty:1,enabled:true,price:null},
        {id:'photo-retouch',group:'Система и производство',name:'Ретушь и чистка фото',unit:'фото',description:'Обычная ручная подготовка исходника без реконструкции товара.',qty:0,enabled:false,price:null},
        {id:'photo-rebuild',group:'Система и производство',name:'Сложная AI-генерация товара',unit:'фото',description:'Восстановление геометрии, материалов, света или недостающих деталей.',qty:0,enabled:false,price:null},
        {id:'master-article',group:'Система и производство',name:'Мастер-шаблон под категорию + 1 SKU',unit:'слайд',description:'Адаптируем систему под категорию и сразу собираем обложку с комплектом внутренних слайдов.',qty:null,multiplierField:'masterSku',enabled:true,price:null},
        {id:'rich-content',group:'Система и производство',name:'Рич-контент категории по ТЗ',unit:'блок',description:'Оформляем рич-контент по вашему ТЗ: собираем блоки в фирменном стиле и адаптируем под категорию товара.',qty:4,enabled:true,price:null},
        {id:'standard-build',group:'Тиражирование',name:'Сборка типового SKU по системе',unit:'слайд',description:'Подстановка товара, характеристик и контента без перестройки шаблона.',qty:null,multiplierField:'standardSku',enabled:true,price:null},
        {id:'refinement-build',group:'Тиражирование',name:'Сборка нетипового SKU с адаптацией',unit:'слайд',description:'Локальная перестройка композиции или компонентов под нетиповой товар.',qty:null,multiplierField:'refinementSku',enabled:true,price:null},
        {id:'modification-build',group:'Тиражирование',name:'Сборка простой модификации',unit:'слайд',description:'Замена цвета, размера, комплектации и связанных характеристик.',qty:null,multiplierField:'modificationSku',enabled:true,price:null}
      ];
      const defaultSettings={totalSku:600,masterSku:0,standardSku:0,refinementSku:0,modificationSku:0};
      function normalizeArtifacts(row){const source=Array.isArray(row.artifacts)?row.artifacts:typeof row.format==='string'?(row.id==='competitor-analysis'?row.format.split(/[,;\n]+/):[row.format]):[];const unique=new Map();source.filter(value=>typeof value==='string').forEach(value=>{const text=value.trim().replace(/\s+/g,' ');if(text&&!unique.has(text.toLocaleLowerCase('ru')))unique.set(text.toLocaleLowerCase('ru'),text)});return[...unique.values()]}
      const defaultState=()=>({schemaVersion:15,settings:clone(defaultSettings),rows:clone(rowDefinitions).map(row=>({...row,firstStage:row.group==='Подготовка и старт проекта',result:row.result||'',artifacts:normalizeArtifacts(row)}))});
      function validNumber(value,fallback){if(value===''||value===null||value===undefined)return fallback;const parsed=Number(value);return Number.isFinite(parsed)&&parsed>=0?parsed:fallback}
      function validInt(value,fallback){const parsed=validNumber(value,null);return parsed!==null&&Number.isInteger(parsed)?parsed:fallback}
      function migrate(saved){const base=defaultState();if(!saved)return base;if(saved.settings?.masterSku!==undefined){const savedSchema=Number(saved.schemaVersion||0),legacyDesign=(saved.rows||[]).find(item=>item.id==='design-system');base.settings={...base.settings,...Object.fromEntries(Object.keys(base.settings).map(key=>[key,validInt(saved.settings?.[key],base.settings[key])]))};base.rows=base.rows.map(row=>{const old=(saved.rows||[]).find(item=>item.id===row.id);if(!old){if(row.id==='design-system-development'&&savedSchema<6&&legacyDesign)return{...row,description:'После A/B-теста выбранный концепт масштабируем на остальные слайды и оформляем в общую дизайн-систему.',result:typeof legacyDesign.result==='string'?legacyDesign.result:''};return row}const compatible=old.multiplierField===row.multiplierField&&old.settingsField===row.settingsField,conceptQty=row.id==='design-system'&&savedSchema<3?3:compatible?validInt(old.qty,row.qty):row.qty,splitConcept=row.id==='design-system'&&savedSchema<6,refreshCompetitor=row.id==='competitor-analysis'&&savedSchema<9,refreshMatrix=row.id==='product-matrix-audit'&&savedSchema<9;return{...row,artifacts:normalizeArtifacts(old),unit:row.id==='design-system-development'&&savedSchema<12?'бренд':refreshCompetitor?'категория':normalizeUnit(old.unit),description:refreshCompetitor?competitorDescription:refreshMatrix?matrixAuditDescription:splitConcept?'На основе анализа конкурентов разрабатываем 3 концепта обложки для A/B-теста CTR.':typeof old.description==='string'?old.description:row.description,result:refreshCompetitor?competitorResult:refreshMatrix?matrixAuditResult:splitConcept?'':typeof old.result==='string'?old.result:'',enabled:typeof old.enabled==='boolean'?old.enabled:row.enabled,firstStage:typeof old.firstStage==='boolean'?old.firstStage:row.firstStage,qty:conceptQty,price:compatible?validNumber(old.price,row.price):null}});(saved.rows||[]).filter(row=>row.custom).forEach(row=>base.rows.push({...row,firstStage:typeof row.firstStage==='boolean'?row.firstStage:false,artifacts:normalizeArtifacts(row),unit:normalizeUnit(row.unit),description:typeof row.description==='string'?row.description:'',result:typeof row.result==='string'?row.result:'',settingsField:undefined,multiplierField:undefined,qty:validInt(row.qty,1),price:validNumber(row.price,null)}));return base}
        const legacyRows=saved.rows||[],legacySettings=saved.settings||{};base.settings={totalSku:validInt(legacySettings.totalSku,600),masterSku:validInt(legacySettings.uniqueSku,0),standardSku:validInt(legacySettings.templateSku,0),refinementSku:validInt(legacySettings.outlierSku,0),modificationSku:validInt(legacySettings.colorSku,0)};
        const priceMap={'photo-retouch':validNumber(legacyRows.find(r=>r.id==='photo-retouch')?.price,null),'photo-rebuild':validNumber(legacyRows.find(r=>r.id==='photo-rebuild')?.price,null)};
        base.rows=base.rows.map(row=>({...row,price:priceMap[row.id]??row.price,qty:row.settingsField?undefined:row.qty}));return base}
      function restoreCurrent(raw){const saved=migrate(raw);if(!clientView)return saved;const fixed=migrate(globalThis.AQUEDUTO_BASE_CALCULATION);fixed.settings=saved.settings;fixed.rows=fixed.rows.map(row=>{const previous=saved.rows.find(item=>item.id===row.id);return previous?{...row,qty:previous.qty,enabled:previous.enabled}:row});return fixed}
      function readCurrent(){try{return restoreCurrent(JSON.parse(localStorage.getItem(STORAGE_KEY))||JSON.parse(localStorage.getItem(LEGACY_KEY))||globalThis.AQUEDUTO_BASE_CALCULATION)}catch(_){return migrate(globalThis.AQUEDUTO_BASE_CALCULATION)}}
      let state=readCurrent();const save=()=>localStorage.setItem(STORAGE_KEY,JSON.stringify(state));
      const parseInput=(input,integer=true)=>{if(input.value==='')return null;const value=Number(input.value);return Number.isFinite(value)&&value>=0&&(!integer||Number.isInteger(value))?value:null};
      const skuFor=row=>row.multiplierField?Math.max(0,Number(state.settings[row.multiplierField])||0):1;
      const qtyFor=row=>Math.max(0,Number(row.qty)||0);
      function allocation(){const total=Math.max(0,Number(state.settings.totalSku)||0),distributed=situations.reduce((sum,item)=>sum+(Number(state.settings[item.field])||0),0);return{total,distributed,complete:total>0&&total===distributed}}
      function rowResult(row){const qty=qtyFor(row),sku=skuFor(row),missingQty=row.enabled&&row.qty===null,active=row.enabled&&sku>0&&(qty>0||missingQty),missing=active&&(missingQty||row.price===null),totalUnits=qty*sku;return{qty,sku,totalUnits,active,missing,missingQty,total:active&&!missing?totalUnits*row.price:0}}
      function calculate(){const volume=allocation();let clientTotal=0,missing=false,active=0;state.rows.forEach(row=>{const result=rowResult(row);if(result.active){active++;clientTotal+=result.total;missing||=result.missing}});return{volume,clientTotal,missing,active}}
      function stageBreakdown(){const names=[...new Set(state.rows.map(row=>row.group))];return names.map(name=>{const rows=state.rows.filter(row=>row.group===name).map(rowResult);return{name,total:rows.reduce((sum,row)=>sum+row.total,0),missing:rows.some(row=>row.missing),active:rows.some(row=>row.active)}})}
      function firstStageSelection(){const rows=state.rows.filter(row=>row.firstStage).map(row=>({row,result:rowResult(row)}));return{rows,total:rows.reduce((sum,item)=>sum+item.result.total,0),incomplete:rows.some(item=>!item.result.active||item.result.missing)}}
      const isComplete=result=>result.volume.complete&&result.active>0&&!result.missing;
      function renderSettings(){Object.keys(defaultSettings).forEach(key=>{const input=document.getElementById(key);if(input)input.value=state.settings[key]??''});renderBalance()}
      function renderBalance(){const value=allocation(),element=$('#volumeBalance');element.textContent=value.complete?`Все ${numberText(value.total)} SKU распределены`:value.distributed<value.total?`Осталось распределить: ${numberText(value.total-value.distributed)}`:`Перебор: ${numberText(value.distributed-value.total)} SKU`;element.classList.toggle('complete',value.complete)}
      let navigationFrame=0;
      function syncSectionNavigation(){const links=[...document.querySelectorAll('.section-nav a')],sections=links.map(link=>document.querySelector(link.hash)).filter(Boolean);if(!sections.length)return;const anchor=Math.min(160,innerHeight*.2);let active=sections[0];sections.forEach(section=>{if(section.getBoundingClientRect().top<=anchor)active=section});links.forEach(link=>{const selected=link.hash==='#'+active.id;link.classList.toggle('active',selected);if(selected)link.setAttribute('aria-current','location');else link.removeAttribute('aria-current')})}
      function scheduleNavigationSync(){if(navigationFrame)return;navigationFrame=requestAnimationFrame(()=>{navigationFrame=0;syncSectionNavigation()})}
      function autoGrow(element){element.style.height='auto';const style=getComputedStyle(element),border=(parseFloat(style.borderTopWidth)||0)+(parseFloat(style.borderBottomWidth)||0);element.style.height=`${element.scrollHeight+border}px`;scheduleNavigationSync()}
      function fitTextFields(){document.querySelectorAll('.stage-meta-field textarea').forEach(autoGrow)}
      const groupIds={'Подготовка и старт проекта':'start','Тестирование':'testing','Система и производство':'system','Тиражирование':'production','Дополнительные работы':'additional'};
      function artifactType(text){const value=text.toLocaleLowerCase('ru');if(/яндекс.*диск|yandex.*disk/.test(value))return'yandex-disk';if(/figma|фигм/.test(value))return'figma';if(/google.*табл|гугл.*табл|google\s*sheets|гугл.*шит/.test(value))return'sheets';if(/\bword\b|ворд|\bdocx?\b/.test(value))return'word';if(/\b(?:jpg|jpeg|png|webp|avif|svg)\b|изображ|фото|картин/.test(value))return'image';if(/смет|калькулятор|интерактив/.test(value))return'calculator';if(/таблиц|\bexcel\b|\bxlsx?\b/.test(value))return'table';return'document'}
      function artifactIcon(text){const type=artifactType(text),names={figma:'Figma',sheets:'Google Таблицы',word:'Word',image:'Изображение',calculator:'Интерактивный расчёт',table:'Таблица','yandex-disk':'Яндекс Диск',document:'Документ'},drawings={
        figma:'<path fill="#F24E1E" d="M7 1a3 3 0 1 0 0 6h3V1z"/><path fill="#FF7262" d="M10 1h3a3 3 0 1 1 0 6h-3z"/><path fill="#A259FF" d="M7 7a3 3 0 1 0 0 6h3V7z"/><circle fill="#1ABCFE" cx="13" cy="10" r="3"/><path fill="#0ACF83" d="M7 13a3 3 0 1 0 3 3v-3z"/>',
        word:'<path fill="#2867B2" d="M7 2h9a1 1 0 0 1 1 1v14a1 1 0 0 1-1 1H7z"/><path d="M9 6h5M9 10h5M9 14h5" stroke="#CDE3FC" stroke-width="1.2" stroke-linecap="round"/><rect x="1" y="5" width="11" height="10" rx="1.5" fill="#154D91"/><path d="m3 8 1.2 4L6 8l1.7 4L9 8" fill="none" stroke="white" stroke-width="1.15" stroke-linecap="round" stroke-linejoin="round"/>',
        sheets:'<path fill="#218C59" d="M5 1.5h7l4 4v12a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1v-15a1 1 0 0 1 1-1z"/><path fill="#82C5A2" d="M12 1.5v4h4z"/><path d="M6.5 8.5h7v6h-7zm0 3h7M10 8.5v6" fill="none" stroke="white" stroke-width="1" stroke-linejoin="round"/>',
        image:'<rect x="2" y="3" width="16" height="14" rx="2.5" fill="#E7F3F7" stroke="#317E9E" stroke-width="1.3"/><circle cx="12.5" cy="7.5" r="1.5" fill="#317E9E"/><path d="m3 14 4.5-5 4 4 2-2 3.5 4" fill="none" stroke="#317E9E" stroke-width="1.3" stroke-linecap="round" stroke-linejoin="round"/>',
        calculator:'<rect x="3.5" y="1.5" width="13" height="17" rx="2.3" fill="#EAF0F7" stroke="#3C5D85" stroke-width="1.3"/><path d="M6.5 5h7v3h-7z" fill="#7195B5"/><path d="M6.5 11h1M11.5 11h2M6.5 14.5h1M11.5 14.5h2" stroke="#3C5D85" stroke-width="1.5" stroke-linecap="round"/>',
        table:'<rect x="2" y="3" width="16" height="14" rx="2" fill="#EDF4F2" stroke="#417C69" stroke-width="1.3"/><path d="M2 8h16M2 12.5h16M8 8v9" stroke="#417C69" stroke-width="1.2"/>',
        document:'<path d="M5 1.5h7l4 4v12a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1v-15a1 1 0 0 1 1-1z" fill="#F0F4F7" stroke="#5C778C" stroke-width="1.2"/><path d="M12 1.5v4h4M7 9h6M7 12h6M7 15h4" fill="none" stroke="#5C778C" stroke-width="1.2" stroke-linecap="round"/>'
      };if(type==='yandex-disk')return`<span class="artifact-type-icon" data-artifact-kind="${type}" title="${names[type]}" aria-hidden="true"><img src="assets/icons/yandex-disk.ico" alt=""></span>`;return`<span class="artifact-type-icon" data-artifact-kind="${type}" title="${names[type]}" aria-hidden="true"><svg viewBox="0 0 20 20" fill="none">${drawings[type]}</svg></span>`}
      function artifactChips(row){if(clientView)return(row.artifacts||[]).map(text=>`<span class="artifact-chip artifact-fixed" role="listitem">${artifactIcon(text)}<span>${esc(text)}</span></span>`).join('');return(row.artifacts||[]).map((text,index)=>`<span class="artifact-chip" role="listitem">${artifactIcon(text)}<span class="artifact-text" contenteditable="plaintext-only" role="textbox" tabindex="0" data-artifact-text="${row.id}" data-artifact-index="${index}" aria-label="Артефакт ${index+1}: ${esc(row.name||row.id)}">${esc(text)}</span><button type="button" data-artifact-remove="${row.id}" data-artifact-index="${index}" aria-label="Удалить артефакт: ${esc(text)}"><svg viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="m6 6 8 8M14 6l-8 8"/></svg></button></span>`).join('')}
      function editArtifact(element,finish=false){const row=state.rows.find(item=>item.id===element.dataset.artifactText),index=Number(element.dataset.artifactIndex);if(!row||!Number.isInteger(index)||index<0||index>=row.artifacts.length)return;let text=element.textContent.trim().replace(/\s+/g,' ');if(!text){if(!finish)return;text=element.dataset.initialText||row.artifacts[index]}row.artifacts[index]=text;if(finish)element.textContent=text;const remove=element.parentElement?.querySelector('[data-artifact-remove]');if(remove)remove.setAttribute('aria-label',`Удалить артефакт: ${text}`);const icon=element.parentElement?.querySelector('.artifact-type-icon');if(icon&&icon.dataset.artifactKind!==artifactType(text))icon.outerHTML=artifactIcon(text);save();scheduleNavigationSync()}
      function refreshArtifacts(row){const list=document.querySelector(`[data-artifact-list="${row.id}"]`);if(list)list.innerHTML=artifactChips(row);scheduleNavigationSync();save()}
      function addArtifact(id){const row=state.rows.find(item=>item.id===id),input=document.querySelector(`[data-artifact-input="${id}"]`);if(!row||!input)return;const text=input.value.trim().replace(/\s+/g,' ');if(!text)return;row.artifacts=normalizeArtifacts({...row,artifacts:[...(row.artifacts||[]),text]});input.value='';refreshArtifacts(row);input.focus()}
      function removeArtifact(id,index){const row=state.rows.find(item=>item.id===id);if(!row||!Number.isInteger(index))return;row.artifacts.splice(index,1);refreshArtifacts(row);document.querySelector(`[data-artifact-input="${id}"]`)?.focus()}
      function renderRows(){
        const groups=[...new Set(state.rows.map(row=>row.group))];
        $('#workRows').innerHTML=groups.map((group,index)=>{
          const cards=state.rows.filter(row=>row.group===group).map(row=>{
            const result=rowResult(row);
            const enabled=`<label class="switch"><input type="checkbox" data-row-id="${row.id}" data-row-field="enabled" ${row.enabled?'checked':''} aria-label="Включено в смету: ${esc(row.name)}"><span class="switch-track" aria-hidden="true"></span><span class="switch-label">Включено в смету</span></label>`;
            const firstStage=`<label class="switch first-stage-switch"><input type="checkbox" data-row-id="${row.id}" data-row-field="firstStage" ${row.firstStage?'checked':''} aria-label="В первый этап: ${esc(row.name)}"><span class="switch-track" aria-hidden="true"></span><span class="switch-label">В первый этап</span></label>`;
            const name=row.custom&&!clientView?`<input type="text" data-row-id="${row.id}" data-row-field="name" value="${esc(row.name)}" aria-label="Название работы">`:esc(row.name);
            const unit=clientView?`<span class="calc-fixed">${esc(unitLabel(row.unit))}</span>`:`<select class="unit-select" data-row-id="${row.id}" data-row-field="unit" aria-label="Единица измерения: ${esc(row.name)}">${unitOptions.map(option=>`<option value="${option}" ${row.unit===option?'selected':''}>${unitLabel(option)}</option>`).join('')}</select>`;
            const sku=row.multiplierField?`<input type="number" min="0" step="1" inputmode="numeric" data-setting-field="${row.multiplierField}" value="${state.settings[row.multiplierField]??''}" placeholder="SKU" aria-label="Количество SKU: ${esc(row.name)}">`:'<span class="calc-dash">—</span>';
            const quantityLabel=row.multiplierField?'Уникальных слайдов на 1 SKU':'Количество';
            const total=!result.active?'<span class="unit">Не включено</span>':result.missingQty?'<span class="missing">Нет количества</span>':result.missing?'<span class="missing">Нет цены</span>':`<span class="money">${money(result.total)}</span>`;
            const formula=row.multiplierField?`<p class="formula" data-derived="${row.id}">${esc(fileQuantity(row))}</p>`:'';
            const estimateNoteText=row.group==='Тиражирование'?productionEstimateNote:row.id==='photo-rebuild'?photoGenerationEstimateNote:'';
            const estimateNote=estimateNoteText?`<p class="formula-note"><span aria-hidden="true">i</span>${esc(estimateNoteText)}</p>`:'';
            return `<article class="stage ${!row.enabled?'stage-disabled':''}" data-row="${row.id}">
              <header class="stage-head"><h3 class="stage-title">${name}</h3><div class="stage-actions">${enabled}${firstStage}${row.custom&&!clientView?`<button class="remove-row" type="button" data-remove-row="${row.id}" aria-label="Удалить строку"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="m6 6 12 12M6 18 18 6"/></svg></button>`:''}</div></header>
              <div class="calculation-grid">
                <label class="calc-field"><span>Единица</span>${unit}</label>
                <label class="calc-field"><span>SKU</span>${sku}</label>
                <label class="calc-field"><span>${quantityLabel}</span><input type="number" min="0" step="1" inputmode="numeric" data-row-id="${row.id}" data-row-field="qty" value="${row.qty??''}" placeholder="Кол-во" aria-label="Количество: ${esc(row.name)}"></label>
                <label class="calc-field"><span>Цена за ед., ₽</span>${clientView?`<span class="calc-fixed">${row.price===null?'Не указана':numberText(row.price)}</span>`:`<input type="number" min="0" step="100" inputmode="decimal" data-row-id="${row.id}" data-row-field="price" value="${row.price??''}" placeholder="Цена" aria-label="Цена за ${esc(row.unit)}: ${esc(row.name)}">`}</label>
                <div class="calc-field calc-total"><span>Стоимость</span><div data-total>${total}</div></div>
                ${formula}${estimateNote}
              </div>
              <div class="stage-content">
                <div class="stage-meta-field"><span>Описание этапа</span>${clientView?`<p class="fixed-copy">${esc(row.description||'')}</p>`:`<textarea rows="1" data-row-id="${row.id}" data-row-field="description" placeholder="Описание этапа" aria-label="Описание этапа: ${esc(row.name)}">${esc(row.description||'')}</textarea>`}</div>
                <div class="stage-meta-field result"><div class="result-heading"><span class="result-icon" aria-hidden="true"><svg viewBox="0 0 24 28" fill="none" stroke="currentColor"><path d="M5 2.5h9l5 5v18H5z"/><path d="M14 2.5v5h5M8.5 13h7M8.5 17h7M8.5 21h4"/></svg></span><span>Что получите</span></div>${clientView?`<p class="fixed-copy result-fixed">${esc(row.result||'')}</p>`:`<label class="result-copy"><textarea rows="1" data-row-id="${row.id}" data-row-field="result" placeholder="Что получаем на выходе" aria-label="Результат этапа: ${esc(row.name)}">${esc(row.result||'')}</textarea></label>`}<div class="artifacts-field"><span class="artifacts-label" id="artifacts-label-${row.id}">В каком виде получите</span><div class="artifact-list" data-artifact-list="${row.id}" role="list" aria-labelledby="artifacts-label-${row.id}">${artifactChips(row)}</div>${clientView?'':`<div class="artifact-entry"><input type="text" data-artifact-input="${row.id}" placeholder="Введите артефакт и нажмите Enter" aria-label="Добавить артефакт: ${esc(row.name)}"><button type="button" data-add-artifact="${row.id}" aria-label="Добавить артефакт: ${esc(row.name)}"><svg viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="M10 4v12M4 10h12"/></svg></button></div>`}</div></div>
              </div>
            </article>`;
          }).join('');
          return `<section class="group-section" id="group-${groupIds[group]||index}" aria-label="${esc(group)}"><header class="group-heading"><div class="group-heading-left"><h2><span class="group-number">Этап ${index+1}.</span> ${esc(group)}</h2></div><span class="group-total" data-group-total="${esc(group)}"></span></header>${cards}</section>`;
        }).join('');
        $('#summaryBreakdown').innerHTML=groups.map(group=>`<div class="summary-line"><span>${esc(group)}</span><strong data-group-total="${esc(group)}"></strong></div>`).join('');
        requestAnimationFrame(fitTextFields);
      }
      function fileQuantity(row){const result=rowResult(row);return `Итоговое количество файлов: ${numberText(result.sku)} SKU × ${numberText(result.qty)} = ${numberText(result.totalUnits)} ${unitPlural(row.unit)}`}
      function refreshRow(id){const row=state.rows.find(item=>item.id===id),element=document.querySelector(`[data-row="${id}"]`);if(!row||!element)return;element.classList.toggle('stage-disabled',!row.enabled);const result=rowResult(row),total=element.querySelector('[data-total]'),derived=element.querySelector('[data-derived]');if(derived)derived.textContent=fileQuantity(row);total.innerHTML=!result.active?'<span class="unit">Не включено</span>':result.missingQty?'<span class="missing">Нет количества</span>':result.missing?'<span class="missing">Нет цены</span>':`<span class="money">${money(result.total)}</span>`}
      function renderTotals(){const result=calculate(),hasAverage=result.active&&result.volume.total>0,average=hasAverage?result.clientTotal/result.volume.total:0;
        $('#liveTotal').textContent=result.active?money(result.clientTotal):'—';
        $('#liveAverage').textContent=hasAverage?money(average):'—';
        const breakdown=stageBreakdown(),stageTotals=new Map(breakdown.map(stage=>[stage.name,stage]));document.querySelectorAll('[data-group-total]').forEach(element=>{const stage=stageTotals.get(element.dataset.groupTotal);element.textContent=stage.missing?money(stage.total)+' *':money(stage.total);element.title=stage.missing?'Не все работы этапа оценены':''});
        const selection=firstStageSelection(),firstStageTotal=$('#firstStageTotal'),firstStageRows=$('#firstStageRows'),firstStageStatus=$('#firstStageStatus');
        if(firstStageRows)firstStageRows.innerHTML=selection.rows.length?selection.rows.map(({row,result})=>`<div class="starting-point-row"><span>${esc(row.name)}</span><strong>${!result.active?'Не включено':result.missing?'Не рассчитано':money(result.total)}</strong></div>`).join(''):'<p class="starting-point-empty">Выберите работы переключателем «В первый этап».</p>';
        if(firstStageTotal)firstStageTotal.textContent=selection.rows.length?money(selection.total):'—';
        if(firstStageStatus){firstStageStatus.textContent=selection.incomplete?'Не все выбранные позиции рассчитаны':'';firstStageStatus.hidden=!selection.incomplete}
      }
      function renderAll(){renderSettings();renderRows();renderTotals();save()}
      function updateSetting(field,input){const value=parseInput(input,true);state.settings[field]=value;document.querySelectorAll(`[data-setting-field="${field}"]`).forEach(element=>{if(element!==input)element.value=value??''});input.setAttribute('aria-invalid',String(input.value!==''&&value===null));renderBalance();state.rows.filter(row=>row.multiplierField===field).forEach(row=>refreshRow(row.id));renderTotals();save()}
      function updateRow(id,field,input){if(clientView&&!['qty','enabled','firstStage'].includes(field))return;const row=state.rows.find(item=>item.id===id);if(!row)return;if(field==='enabled'){row.enabled=input.checked;requestAnimationFrame(fitTextFields)}else if(field==='firstStage')row.firstStage=input.checked;else if(['qty','price'].includes(field)){const value=parseInput(input,field==='qty');row[field]=value;input.setAttribute('aria-invalid',String(input.value!==''&&value===null))}else row[field]=field==='unit'?normalizeUnit(input.value):input.value;if(field==='unit'){renderRows();renderTotals();save();return}refreshRow(id);renderTotals();save()}
      function showToast(message){const toast=$('#toast');toast.textContent=message;toast.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove('show'),2200)}
      function addRow(){const id=`custom-${Date.now()}`,index=state.rows.length;state.rows.splice(index,0,{id,group:'Дополнительные работы',name:'Новая работа',unit:'слайд',description:'Дополнительная работа вне базового процесса.',result:'',artifacts:[],qty:1,enabled:true,firstStage:false,price:null,custom:true});renderAll();requestAnimationFrame(()=>document.querySelector(`[data-row-id="${id}"][data-row-field="name"]`)?.focus())}

      function exportData(){
        const result=calculate(),breakdown=stageBreakdown(),selection=firstStageSelection();
        return {total:result.clientTotal,totalSku:result.volume.total,active:result.active,complete:isComplete(result),average:result.active&&result.volume.total>0?result.clientTotal/result.volume.total:null,
          stages:breakdown.map(stage=>({...stage,rows:state.rows.filter(row=>row.group===stage.name&&rowResult(row).active).map(row=>({...clone(row),...rowResult(row),unit:unitLabel(row.unit),multiplier:!!row.multiplierField,formula:row.multiplierField?fileQuantity(row):'',estimateNote:row.group==='Тиражирование'?productionEstimateNote:row.id==='photo-rebuild'?photoGenerationEstimateNote:''}))})),
          firstStage:{total:selection.total,incomplete:selection.incomplete,rows:selection.rows.map(({row,result})=>({name:row.name,total:result.total,active:result.active,missing:result.missing}))},
          disclaimer:$('#estimateDisclaimer').textContent,
          terms:[...document.querySelectorAll('.payment-terms-grid>div')].map(el=>({title:el.querySelector('h4').textContent,text:el.querySelector('p').textContent}))};
      }
      async function downloadCalculation(){
        if(clientView)return;
        const button=$('#saveBtn');button.disabled=true;button.setAttribute('aria-busy','true');button.textContent='Готовим PDF…';
        try{save();await AquedutoPdf.download(exportData());showToast('PDF скачан')}
        catch(error){console.error('PDF export failed',error);showToast('Не удалось создать PDF. Повторите попытку.')}
        finally{button.disabled=false;button.removeAttribute('aria-busy');button.textContent='Сохранить расчёт'}
      }

      $('#workRows').addEventListener('focusin',event=>{if(event.target.matches('[data-artifact-text]'))event.target.dataset.initialText=event.target.textContent});
      $('#workRows').addEventListener('focusout',event=>{if(event.target.matches('[data-artifact-text]'))editArtifact(event.target,true)});
      $('#workRows').addEventListener('input',event=>{if(event.target.matches('[data-artifact-text]'))editArtifact(event.target)});
      $('#workRows').addEventListener('keydown',event=>{if(event.isComposing)return;if(event.target.matches('[data-artifact-text]')){if(event.key==='Enter'){event.preventDefault();editArtifact(event.target,true);event.target.blur()}else if(event.key==='Escape'){event.preventDefault();event.target.textContent=event.target.dataset.initialText||event.target.textContent;editArtifact(event.target,true);event.target.blur()}return}if(event.key==='Enter'&&event.target.matches('[data-artifact-input]')){event.preventDefault();addArtifact(event.target.dataset.artifactInput)}});
      $('#workRows').addEventListener('click',event=>{const add=event.target.closest('[data-add-artifact]');if(add){addArtifact(add.dataset.addArtifact);return}const remove=event.target.closest('[data-artifact-remove]');if(remove)removeArtifact(remove.dataset.artifactRemove,Number(remove.dataset.artifactIndex))});
      $('#workRows').addEventListener('input',event=>{const settingInput=event.target.closest('[data-setting-field]');if(settingInput){updateSetting(settingInput.dataset.settingField,settingInput);return}const input=event.target.closest('[data-row-field]');if(input&&input.type!=='checkbox'&&input.tagName!=='SELECT'){if(input.tagName==='TEXTAREA')autoGrow(input);updateRow(input.dataset.rowId,input.dataset.rowField,input)}});$('#workRows').addEventListener('change',event=>{const input=event.target.closest('[data-row-field]');if(input&&(input.type==='checkbox'||input.tagName==='SELECT'))updateRow(input.dataset.rowId,input.dataset.rowField,input)});$('#workRows').addEventListener('click',event=>{const toggle=event.target.closest('[data-toggle-meta]');if(toggle){const meta=document.querySelector(`[data-meta-row="${toggle.dataset.toggleMeta}"]`),willOpen=meta?.hasAttribute('hidden');if(meta){meta.toggleAttribute('hidden',!willOpen);toggle.setAttribute('aria-expanded',String(willOpen));if(willOpen)requestAnimationFrame(()=>meta.querySelectorAll('textarea').forEach(autoGrow))}return}const button=event.target.closest('[data-remove-row]');if(!button)return;state.rows=state.rows.filter(row=>row.id!==button.dataset.removeRow);renderAll()});$('#totalSku').addEventListener('input',event=>updateSetting('totalSku',event.target));if(!clientView){$('#addRowBtn').addEventListener('click',addRow);$('#saveBtn').addEventListener('click',downloadCalculation)}window.addEventListener('resize',fitTextFields);window.addEventListener('beforeprint',fitTextFields);window.addEventListener('afterprint',fitTextFields);renderAll();document.fonts.ready.then(fitTextFields);
      window.addEventListener('scroll',scheduleNavigationSync,{passive:true});window.addEventListener('hashchange',scheduleNavigationSync);scheduleNavigationSync();
    })();
